// Include packages needed for this application
const inquirer = require('inquirer');
const fs = require('fs');
// below is a "local" require not from npm
const generateMarkdown = require('./utils/generateMarkdown')

// Function to write README file in a separate subdirectory
function writeToFile(fileName, data) {
  const outputDir = './output'

  // separate directory for generated READMEs
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir);
  }

  fileName = outputDir + '/' + fileName;
  fs.writeFile(fileName, generateMarkdown(data), err => {
    if (err) console.log(err);
  });
}

// Function to initialize app
function init() {
  // collect question prompts; properties match data object generated by user input
  const prompt = {
    title: 'What is your project TITLE?',
    description: 'Describe your project',
    license: 'Choose a license (choosealicense.com or opensource.org/licenses/)',
    installation: 'Describe the installation process.',
    usage: 'Explain how the project is used.',
    github: 'GitHub user name:',
    email: 'Email:',
    contribute: 'Contribution instructions (leave blank to omit):',
    test: 'Testing instructions (leave blank to omit):'
  };

  // prompt for input using inquirer
  inquirer.prompt([
    {type: 'input', name: 'title', message: prompt.title,
     validate: value => {
       if (!value) return "A project title is required.";
       else return true;
     }
    },
    {type: 'editor', name: 'description', message: prompt.description,
     validate: value => {
       if (!value) return "A description is required. Did you quit the editor before saving? (:wq in vim)";
       else return true;
     }
    },
    {type: 'list', name: 'license', message: prompt.license,
      choices: ['MIT', 'Apache', 'BSD2', 'BSD3', 'ISC', 'GPLv3', 'none'],
    },
    {type: 'editor', name: 'installation', prompt: prompt.installation,
     validate: value => {
       if (!value) return "Installation instructions are required. Did you quit the editor before saving? (:wq in vim)";
       else return true;
     }
    },
    {type: 'editor', name: 'usage', message: prompt.usage,
     validate: value => {
       if (!value) return "A description of app usage is required. Did you quit the editor before saving? (:wq in vim)";
       else return true;
     }
    },
    {type: 'input', name: 'github', message: prompt.github,},
    {type: 'input', name: 'email', message: prompt.email,},
    {type: 'input', name: 'contribute', message: prompt.contribute,},
    {type: 'input', name: 'test', message: prompt.test,}
  ])
    .then(data => {
      const filename = data.title.split(' ').join('') + "-README.md";
      if (data.license === 'none') data.license = '';
      writeToFile(filename, data);
    });
}

// Function call to initialize app
init();
